### ISSUE TITLE
Error in setup decoding file

### ISSUE THREAD

**Issue by AnkithKala** [CSS-Electronics/can_decoder#2]
Hi

I am getting this below issue while running setup_decoding_rules.py file 

arxml is not supported
Traceback (most recent call last):
  File "C:\Users\kalaa\AppData\Local\Programs\Python\Python37\lib\site-packages\canmatrix\formats\__init__.py", line 27, in <module>
    importlib.import_module("canmatrix.formats." + module)
  File "C:\Users\kalaa\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\kalaa\AppData\Local\Programs\Python\Python37\lib\site-packages\canmatrix\formats\arxml.py", line 34, in <module>
    import lxml.etree
ModuleNotFoundError: No module named 'lxml'
kcd is not supported
Traceback (most recent call last):
  File "C:\Users\kalaa\AppData\Local\Programs\Python\Python37\lib\site-packages\canmatrix\formats\__init__.py", line 27, in <module>
    importlib.import_module("canmatrix.formats." + module)
  File "C:\Users\kalaa\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\kalaa\AppData\Local\Programs\Python\Python37\lib\site-packages\canmatrix\formats\kcd.py", line 35, in <module>
    import lxml.etree
ModuleNotFoundError: No module named 'lxml'
fibex is not supported
Traceback (most recent call last):
  File "C:\Users\kalaa\AppData\Local\Programs\Python\Python37\lib\site-packages\canmatrix\formats\__init__.py", line 27, in <module>
    importlib.import_module("canmatrix.formats." + module)
  File "C:\Users\kalaa\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\kalaa\AppData\Local\Programs\Python\Python37\lib\site-packages\canmatrix\formats\fibex.py", line 33, in <module>
    import lxml.etree
ModuleNotFoundError: No module named 'lxml'
xls is not supported
Traceback (most recent call last):
  File "C:\Users\kalaa\AppData\Local\Programs\Python\Python37\lib\site-packages\canmatrix\formats\__init__.py", line 27, in <module>
    importlib.import_module("canmatrix.formats." + module)
  File "C:\Users\kalaa\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\kalaa\AppData\Local\Programs\Python\Python37\lib\site-packages\canmatrix\formats\xls.py", line 34, in <module>
    import xlrd
ModuleNotFoundError: No module named 'xlrd'
xlsx is not supported
Traceback (most recent call last):
  File "C:\Users\kalaa\AppData\Local\Programs\Python\Python37\lib\site-packages\canmatrix\formats\__init__.py", line 27, in <module>
    importlib.import_module("canmatrix.formats." + module)
  File "C:\Users\kalaa\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\kalaa\AppData\Local\Programs\Python\Python37\lib\site-packages\canmatrix\formats\xlsx.py", line 32, in <module>
    import xlsxwriter
ModuleNotFoundError: No module named 'xlsxwriter'
yaml is not supported
Traceback (most recent call last):
  File "C:\Users\kalaa\AppData\Local\Programs\Python\Python37\lib\site-packages\canmatrix\formats\__init__.py", line 27, in <module>
    importlib.import_module("canmatrix.formats." + module)
  File "C:\Users\kalaa\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\kalaa\AppData\Local\Programs\Python\Python37\lib\site-packages\canmatrix\formats\yaml.py", line 32, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Traceback (most recent call last):
  File "C:\Users\kalaa\OneDrive\Desktop\can_decoder\examples\setup_decoding_rules.py", line 143, in <module>
    example_setup_decoding_rules_j1939()
  File "C:\Users\kalaa\OneDrive\Desktop\can_decoder\examples\setup_decoding_rules.py", line 72, in example_setup_decoding_rules_j1939
    decoded_result = decode_using_rules(handle, db)
  File "C:\Users\kalaa\OneDrive\Desktop\can_decoder\examples\setup_decoding_rules.py", line 30, in decode_using_rules
    mdf_file = mdf_iter.MdfFile(handle)
RuntimeError: Buffer error

**Comment by MatinF** [comment]
Hi there, can you please share the full script, log file and DBC file you're trying to use?

**Comment by dapperfu** [comment]
From the debug error it looks like you're missing a lot of requirements.

yaml, lxml, & xlsxwriter

Could you install those and try again?

**Comment by MatinF** [comment]
Closing issue as no further info provided
